FROM node:20 AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npx prisma generate && npm run build && rm -rf node_modules

FROM node:20-slim
WORKDIR /app
COPY --from=build /app/dist .

ENV DATABASE_URL=mysql://johndoe:randompassword@localhost:3306/mydb
EXPOSE 3000
ENTRYPOINT ["node", "main"]


