CREATE USER 'exporter'@'%' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'cloud_canvas_user'@'%';
FLUSH PRIVILEGES;